name: Build and Push Docker Image

on:
  # To enable manual triggering of this workflow
  workflow_dispatch:

  # Trigger for pushes to master and tags
  push:
    branches:
      - master
      - develop
    tags:
      - 'v*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: index.docker.io/metacall/core

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        run: docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" -p "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"

      - name: Pull MetaCall Docker Images
        run: bash ./docker-compose.sh pull

      - name: Build MetaCall Docker Images
        run: bash ./docker-compose.sh build

      # TODO: Build with alpine and provide multiple tags (debian & alpine) once all tests pass
      - name: Push MetaCall Docker Image to DockerHub
        run: |
          if [[ "${{ github.ref == 'refs/heads/master' }}" = true ]]; then
            bash ./docker-compose.sh push
          elif [[ "${{ contains(github.ref, 'refs/tags/') }}" = true ]]; then
            bash ./docker-compose.sh version
          fi

      - name: Logout from DockerHub
        run: docker logout
