name: Build and Push Docker Image for Multiple Architectures

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
      - feature/**
    tags:
      - 'v*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: mryash/core

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
          - linux/arm/v6
          - linux/arm/v7
        service:
          - deps
          - dev
          - runtime
          - cli
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Define Platform and Service
        id: define-platform-service
        run: |
          PLATFORM=${{ matrix.platform }}
          PLATFORM_SAFE=${PLATFORM//\//-} # Replace slashes with dashes
          SERVICE=${{ matrix.service }}
          echo "METACALL_PLATFORM=${PLATFORM}" >> $GITHUB_ENV
          echo "METACALL_PLATFORM_SAFE=${PLATFORM_SAFE}" >> $GITHUB_ENV
          echo "METACALL_SERVICE=${SERVICE}" >> $GITHUB_ENV

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build MetaCall Docker Images
        run: |
          docker buildx build \
            --platform ${{ matrix.platform }} \
            --file ./Dockerfile.${{ matrix.service }} \
            --tag ${{ env.IMAGE_NAME }}:${{ matrix.service }}-${{ env.METACALL_PLATFORM_SAFE }} \
            --push \
            .

      - name: Export Digest
        run: |
          mkdir -p /tmp/digests
          digest=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ env.IMAGE_NAME }}:${{ matrix.service }}-${{ env.METACALL_PLATFORM_SAFE }})
          touch "/tmp/digests/${{ matrix.service }}-${{ env.METACALL_PLATFORM_SAFE }}_${digest#sha256:}"

      - name: Upload Digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.service }}-${{ env.METACALL_PLATFORM_SAFE }}
          path: /tmp/digests/*
          retention-days: 1

          
  merge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all digests
        uses: actions/download-artifact@v4
        with:
          pattern: digests-*
          path: /tmp/digests
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Create Manifest List (without pushing)
        run: |
          platforms=("linux-amd64" "linux-arm64" "linux-arm-v6" "linux-arm-v7")
          manifests=""
          for platform in "${platforms[@]}"; do
            digest=$(cat /tmp/digests/${platform}_*)
            manifests="${manifests} ${IMAGE_NAME}@${digest}"
          done
          echo "Would create manifest list with: ${manifests}"
          echo "Would tag as: ${IMAGE_NAME}:${{ steps.meta.outputs.version }} and ${IMAGE_NAME}:latest"

      - name: Simulate Image Inspection
        run: |
          echo "Would inspect: ${IMAGE_NAME}:${{ steps.meta.outputs.version }}"
          echo "Would inspect: ${IMAGE_NAME}:latest"

      # - name: Logout from DockerHub
      #   if: always()
      #   run: docker logout
