name: Build and Push Docker Image for Multiple Architectures

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
      - feature/** # Added to run on feature branches
    tags:
      - 'v*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: index.docker.io/metacall/core

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
          - linux/arm/v6
          - linux/arm/v7

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Define Platform
        run: |
          PLATFORM=${{ matrix.platform }}
          echo "METACALL_PLATFORM=${PLATFORM}" >> $GITHUB_ENV
          echo "METACALL_PLATFORM_PAIR=${PLATFORM//\//-}" >> $GITHUB_ENV

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Login to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build MetaCall Docker Images
        id: build_image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Export Digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build_image.outputs.digest }}"
          touch "/tmp/digests/${METACALL_PLATFORM_PAIR}_${digest#sha256:}"

      - name: Upload Digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ github.run_id }}-${{ github.job }}-${{ github.run_attempt }}-${{ runner.os }}-${{ matrix.platform }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

      # - name: Logout from DockerHub
      #   if: always()
      #   run: docker logout

  merge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Digests
        uses: actions/download-artifact@v4
        with:
          name: digests-${{ github.run_id }}-${{ github.job }} # Match the uploaded artifact name
          path: /tmp/digests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      # - name: Login to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Create Manifest List (without pushing)
        run: |
          platforms=("linux-amd64" "linux-arm64" "linux-arm-v6" "linux-arm-v7")
          manifests=""
          for platform in "${platforms[@]}"; do
            digest=$(cat /tmp/digests/${platform}_*)
            manifests="${manifests} ${IMAGE_NAME}@${digest}"
          done
          echo "Would create manifest list with: ${manifests}"
          echo "Would tag as: ${IMAGE_NAME}:${{ steps.meta.outputs.version }} and ${IMAGE_NAME}:latest"

      - name: Simulate Image Inspection
        run: |
          echo "Would inspect: ${IMAGE_NAME}:${{ steps.meta.outputs.version }}"
          echo "Would inspect: ${IMAGE_NAME}:latest"

      # - name: Logout from DockerHub
      #   if: always()
      #   run: docker logout
