name: Linux Sanitizer Test

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - master
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  linux-sanitizer-gcc:
    name: Linux GCC Sanitizer Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image: ["debian:trixie-slim", "debian:bookworm-slim", "ubuntu:jammy", "ubuntu:mantic"]
        sanitizer: [address-sanitizer, thread-sanitizer] # TODO: memory-sanitizer not supported by GCC

    env:
      SANITIZER_SKIP_SUMMARY: 1

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install, build and run thread sanitizer tests
        run: ./docker-compose.sh test-${{ matrix.sanitizer }}
        env:
          METACALL_BUILD_TYPE: debug
          METACALL_BASE_IMAGE: ${{ matrix.image }}
